# Generated by Django 5.2.6 on 2025-10-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='is_published',
        ),
    ]
