# Generated by Django 5.2.6 on 2025-10-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0002_remove_notice_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='notice',
            name='topic',
            field=models.CharField(choices=[('admission', 'ADMISSION'), ('exam', 'EXAM'), ('event', 'EVENT'), ('holiday', 'HOLIDAY'), ('general', 'GENERAL')], default='general', max_length=10),
        ),
    ]
