# Generated by Django 5.2.6 on 2025-10-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0003_notice_priority_notice_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='rank',
            field=models.IntegerField(default=0, help_text='Rank will determine the order of apparance, Lower the rank, higher the appparance', unique=True),
        ),
    ]
