# Generated by Django 5.2.6 on 2025-10-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0005_alter_teachers_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='rank',
            field=models.IntegerField(blank=True, default=0, help_text='Rank will determine the order of apparance, Lower the rank, higher the appparance', null=True),
        ),
    ]
