# Generated by Django 5.2.6 on 2025-10-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0007_remove_teachers_rank_teachers_trank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='trank',
            field=models.IntegerField(blank=True, help_text='Rank will determine the order of apparance, Lower the rank, higher the appparance', null=True),
        ),
    ]
