# Generated by Django 5.2.6 on 2025-10-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0008_alter_teachers_trank'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='trank',
            field=models.IntegerField(default=0, help_text='Rank will determine the order of apparance, Lower the rank, higher the appparance'),
        ),
    ]
