# Generated by Django 5.2.6 on 2025-10-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0009_teachers_slug_alter_teachers_trank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
