# Generated by Django 5.2.6 on 2025-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0010_alter_teachers_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='slug',
        ),
        migrations.AddField(
            model_name='teachers',
            name='tslug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
