# Generated by Django 5.2.6 on 2025-11-11 19:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pweb', '0011_remove_teachers_slug_teachers_tslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='education',
            field=models.TextField(blank=True, help_text='Write educational qualification as text / paragraph here', null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='experience',
            field=models.TextField(blank=True, help_text='Example: 5 years', null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subject',
            field=models.CharField(blank=True, help_text='mathematics, science, English, Bangla, Social-science, Ict, Islam etc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='tslug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
